 
name: Remote Dispatch Action Initiator

on:
  push:
  repository_dispatch:
  workflow_dispatch:
  
env:
  SUPER_SECRET: ${{ secrets.Testing }}

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: PING - Dispatch initiating repository event
        if: github.event.action != 'pong'
        run: |
         curl --location --request POST 'https://api.github.com/repos/NickReid89/actions-remote-dispatch-c/dispatches' \
         --header 'Accept;' \
         --header 'Authorization: Bearer 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' \
         --header 'Content-Type: text/plain' \
         --data-raw '{
            "event_type":"ping",
            "client_payload":{
               "repository":"actions-remote-dispatch-c"
            }
         }'
      - name: ACK - Acknowledge pong from remote repository
        if: github.event.action == 'pong'
        run: |
          echo "PONG received from '${{ github.event.client_payload.repository }}'" && \
          curl --location --request POST 'https://api.github.com/repos/NickReid89/actions-remote-dispatch-c/dispatches' \
          --header 'Accept;' \
          --header 'Authorization: Bearer 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' \
          --header 'Content-Type: text/plain' \
          --data-raw '{
             "event_type":"ack",
             "client_payload":{
                "repository":"actions-remote-dispatch-c"
             }
          }'
