 
name: Remote Dispatch Action Initiator

on:
  push:
  repository_dispatch:
  workflow_dispatch:
  
env:
  SUPER_SECRET: ${{ secrets.Testing }}

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: PING - Dispatch initiating repository event
        if: github.event.action != 'pong'
        run: |
         curl --location --request POST 'https://api.github.com/repos/NickReid89/actions-remote-dispatch-c/dispatches' \
         --header 'Accept;' \
         --header 'Authorization: Bearer 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' \
         --header 'Content-Type: text/plain' \
         --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      - name: ACK - Acknowledge pong from remote repository
        if: github.event.action == 'pong'
        run: |
          echo "PONG received from '${{ github.event.client_payload.repository }}'" && \
          curl --location --request POST 'https://api.github.com/repos/NickReid89/actions-remote-dispatch-c/dispatches' \
          --header 'Accept;' \
          --header 'Authorization: Bearer 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' \
          --header 'Content-Type: text/plain' \
          --data '{"event_type": "ack", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
          
      - name: ACK - Store value
        if: github.event.action == 'pong'
        run: |        
          echo "MICROSERVICE_NAME=$(sed -e 's/^"//' -e 's/"$//' <<<"${{ github.event.client_payload.testing }}" )" >> $GITHUB_ENV
          echo "action_state=yellow" >> $GITHUB_ENV
          
      - name: ACK - Print value
        if: github.event.action == 'pong'
        run: |
          echo "PONG received from '${{ github.event.client_payload.repository }}'" 
          echo "${{ env.MICROSERVICE_NAME }} "
          echo "${{ env.action_state }}" # This will output 'yellow'
          
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: NickReid89/actions-remote-dispatch-c

      - name: list files
        run: pwd
      
